export type Typography = {
	fonts: {
    body: string,
    heading: string,
    mono: string,
  },
  fontSizes: {
    xs: string,
    sm: string,
    md: string,
    lg: string,
    xl: string,
    "2xl": string,
    "3xl": string,
    "4xl": string,
    "5xl": string,
    "6xl": string,
    "7xl": string,
    "8xl": string,
    "9xl": string,
  },
  fontWeights: {
    hairline: number,
    thin: number,
    light: number,
    normal: number,
    medium: number,
    semibold: number,
    bold: number,
    extrabold: number,
    black: number,
  },
  lineHeights: {
    normal: string | number,
    none: string | number,
    shorter: string | number,
    short: string | number,
    base: string | number,
    tall: string | number,
    taller: string | number,
    "3": string | number,
    "4": string | number,
    "5": string | number,
    "6": string | number,
    "7": string | number,
    "8": string | number,
    "9": string | number,
    "10": string | number,
  },
  letterSpacings: {
    tighter: string,
    tight: string,
    normal: string,
    wide: string,
    wider: string,
    widest: string,
  },
}